In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Hr_data.csv')

In [3]:
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [4]:
df.isna().sum()

employee_id              0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
department               0
salary                   0
dtype: int64

In [5]:
df.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [6]:
df.columns

Index(['employee_id', 'number_project', 'average_montly_hours',
       'time_spend_company', 'Work_accident', 'left', 'promotion_last_5years',
       'department', 'salary'],
      dtype='str')

In [7]:
df.rename(columns={'employee_id' : 'Employee_ID', 'number_project' : 'Number_of_Projects', 'average_montly_hours' : 'Average_Monthly_Hours',
       'time_spend_company' : 'Time_Spent_in_Company', 'Work_accident' : 'Work_Accident', 'left' : 'Left', 'promotion_last_5years' : 'Promoted_in_Last_5_Years',
       'department' : 'Department', 'salary' : 'Salary '}, inplace=True)

In [8]:
df

,Employee_ID,Number_of_Projects,Average_Monthly_Hours,Time_Spent_in_Company,Work_Accident,Left,Promoted_in_Last_5_Years,Department,Salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [9]:
df['Department'].value_counts()

Department
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64

In [10]:
df.columns

Index(['Employee_ID', 'Number_of_Projects', 'Average_Monthly_Hours',
       'Time_Spent_in_Company', 'Work_Accident', 'Left',
       'Promoted_in_Last_5_Years', 'Department', 'Salary '],
      dtype='str')

In [11]:
df.loc[df['Salary '] == 'low', ['Employee_ID','Department', 'Salary ']]

       Employee_ID Department Salary
0             1003      sales     low
3             1038      sales     low
4             1057      sales     low
5             1060      sales     low
6             1061      sales     low
...            ...        ...     ...
14994        87670    support     low
14995        87673    support     low
14996        87679    support     low
14997        87681    support     low
14998        87684    support     low

[7316 rows x 3 columns]

In [12]:
df.iloc[0:5, 0:5]

,Employee_ID,Number_of_Projects,Average_Monthly_Hours,Time_Spent_in_Company,Work_Accident
0,1003,2,157,3,0
1,1005,5,262,6,0
2,1486,7,272,4,0
3,1038,5,223,5,0
4,1057,2,159,3,0

In [13]:
df['Department'].unique()

<ArrowStringArray>
[      'sales',  'accounting',          'hr',   'technical',     'support',
  'management',          'IT', 'product_mng',   'marketing',       'RandD']
Length: 10, dtype: str

In [14]:
df.loc[df['Department'].isin(['Sales', 'IT'])]

,Employee_ID,Number_of_Projects,Average_Monthly_Hours,Time_Spent_in_Company,Work_Accident,Left,Promoted_in_Last_5_Years,Department,Salary
61,1399,7,308,4,0,1,0,IT,medium
62,1404,6,244,5,0,1,0,IT,medium
63,1413,2,132,3,0,1,0,IT,medium
64,42423,6,286,4,0,1,0,IT,medium
65,1424,6,161,4,0,1,0,IT,medium
...,...,...,...,...,...,...,...,...,...
14930,87284,6,268,4,0,1,0,IT,medium
14931,87288,5,240,5,0,1,0,IT,medium
14932,87294,2,127,3,0,1,0,IT,medium
14933,87308,7,264,4,0,1,0,IT,medium
14938,45511,4,271,5,0,1,0,IT,medium

In [15]:
df['Department'].value_counts()

Department
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64

In [16]:
grp = df.groupby('Department')

In [17]:
grp.groups

{'IT': [61, 62, 63, 64, 65, 70, 138, 139, 140, 141, 142, 147, 214, 215, 216, 217, 218, 223, 291, 292, 293, 294, 295, 300, 367, 368, 369, 370, 371, 376, 443, 444, 445, 446, 447, 452, 519, 520, 521, 522, 523, 528, 595, 596, 597, 598, 599, 604, 671, 672, 673, 674, 675, 680, 747, 748, 749, 750, 751, 756, 823, 824, 825, 826, 827, 832, 899, 900, 901, 902, 903, 908, 975, 976, 977, 978, 979, 984, 1051, 1052, 1053, 1054, 1055, 1060, 1127, 1128, 1129, 1130, 1131, 1136, 1204, 1205, 1206, 1207, 1208, 1213, 1214, 1215, 1216, 1281, ...], 'RandD': [301, 302, 303, 304, 305, 453, 454, 455, 456, 457, 605, 606, 607, 608, 609, 833, 834, 835, 836, 837, 985, 986, 987, 988, 989, 1061, 1062, 1063, 1064, 1065, 1217, 1218, 1219, 1291, 1292, 1293, 1294, 1295, 1296, 1368, 1369, 1370, 1371, 1372, 1373, 1445, 1446, 1447, 1448, 1449, 1450, 1522, 1523, 1524, 1525, 1526, 1598, 1599, 1600, 1601, 1602, 1675, 1676, 1677, 1678, 1679, 1751, 1752, 1753, 1754, 1755, 1827, 1828, 1829, 1830, 1831, 1903, 1904, 1905, 1906, 1907, 1979, 1980, 1981, 1982, 1983, 2055, 2056, 2057, 2058, 2059, 2131, 2132, 2133, 2134, 2135, 2207, 2208, 2209, 2210, ...], 'accounting': [28, 29, 30, 79, 105, 106, 107, 155, 181, 182, 183, 224, 225, 232, 258, 259, 260, 308, 334, 335, 336, 377, 378, 384, 410, 411, 412, 460, 486, 487, 488, 529, 530, 536, 562, 563, 564, 612, 638, 639, 640, 688, 714, 715, 716, 764, 790, 791, 792, 840, 866, 867, 868, 916, 942, 943, 944, 992, 1018, 1019, 1020, 1068, 1094, 1095, 1096, 1145, 1171, 1172, 1173, 1222, 1248, 1249, 1250, 1299, 1325, 1326, 1327, 1376, 1402, 1403, 1404, 1453, 1479, 1480, 1481, 1529, 1555, 1556, 1557, 1606, 1632, 1633, 1634, 1682, 1708, 1709, 1710, 1758, 1784, 1785, ...], 'hr': [31, 32, 33, 34, 108, 109, 110, 111, 184, 185, 186, 187, 226, 227, 228, 261, 262, 263, 264, 337, 338, 339, 340, 379, 380, 381, 413, 414, 415, 416, 489, 490, 491, 492, 531, 532, 533, 565, 566, 567, 568, 641, 642, 643, 644, 717, 718, 719, 720, 793, 794, 795, 796, 869, 870, 871, 872, 945, 946, 947, 948, 1021, 1022, 1023, 1024, 1097, 1098, 1099, 1100, 1174, 1175, 1176, 1177, 1251, 1252, 1253, 1254, 1328, 1329, 1330, 1331, 1405, 1406, 1407, 1408, 1482, 1483, 1484, 1485, 1558, 1559, 1560, 1561, 1635, 1636, 1637, 1638, 1711, 1712, 1713, ...], 'management': [60, 82, 137, 158, 213, 235, 290, 311, 366, 387, 442, 463, 518, 539, 594, 615, 670, 691, 746, 767, 822, 843, 898, 919, 974, 995, 1050, 1071, 1126, 1148, 1203, 1225, 1280, 1302, 1357, 1379, 1434, 1456, 1511, 1532, 1587, 1609, 1664, 1685, 1740, 1761, 1816, 1837, 1892, 1913, 1968, 1989, 2044, 2065, 2120, 2141, 2196, 2217, 2272, 2293, 2348, 2369, 2424, 2445, 2500, 2522, 2577, 2599, 2654, 2676, 2731, 2753, 2808, 2830, 2885, 2906, 2961, 2983, 3038, 3059, 3114, 3135, 3190, 3211, 3266, 3287, 3342, 3363, 3418, 3439, 3494, 3515, 3570, 3591, 3646, 3667, 3722, 3743, 3798, 3819, ...], 'marketing': [77, 83, 84, 85, 148, 149, 150, 151, 152, 153, 159, 160, 161, 229, 230, 236, 237, 238, 306, 312, 313, 314, 382, 388, 389, 390, 458, 464, 465, 466, 534, 540, 541, 542, 610, 616, 617, 618, 686, 692, 693, 694, 762, 768, 769, 770, 838, 844, 845, 846, 914, 920, 921, 922, 990, 996, 997, 998, 1066, 1072, 1073, 1074, 1142, 1143, 1149, 1150, 1151, 1220, 1226, 1227, 1228, 1297, 1303, 1304, 1305, 1374, 1380, 1381, 1382, 1451, 1457, 1458, 1459, 1527, 1533, 1534, 1535, 1603, 1604, 1610, 1611, 1612, 1680, 1686, 1687, 1688, 1756, 1762, 1763, 1764, ...], 'product_mng': [66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 143, 144, 145, 146, 219, 220, 221, 222, 296, 297, 298, 299, 372, 373, 374, 375, 448, 449, 450, 451, 524, 525, 526, 527, 600, 601, 602, 603, 676, 677, 678, 679, 752, 753, 754, 755, 828, 829, 830, 831, 904, 905, 906, 907, 980, 981, 982, 983, 1056, 1057, 1058, 1059, 1132, 1133, 1134, 1135, 1209, 1210, 1211, 1212, 1286, 1287, 1288, 1289, 1363, 1364, 1365, 1366, 1440, 1441, 1442, 1443, 1517, 1518, 1519, 1520, 1593, 1594, 1595, 1596, 1670, 1671, 1672, 1673, 1746, 1747, 1748, 1749, 1822, 1823, ...], 'sales': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 78, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 154, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 231, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 307, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, ...], 'support': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 80, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 156, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 233, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 309, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 385, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 461, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 537, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 613, 656, 657, 658, 659, ...], 'technical': [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 57, 58, 59, 81, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 134, 135, 136, 157, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 210, 211, 212, 234, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 287, 288, 289, 310, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 363, 364, 365, 386, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 439, 440, 441, 462, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, ...]}

In [18]:
grp_it = grp.get_group('IT')

In [19]:
grp_sales = grp.get_group('sales')

In [20]:
grp_it['Average_Monthly_Hours'].mean()

np.float64(202.2159739201304)

In [21]:
grp_sales.count()

Employee_ID                 4140
Number_of_Projects          4140
Average_Monthly_Hours       4140
Time_Spent_in_Company       4140
Work_Accident               4140
Left                        4140
Promoted_in_Last_5_Years    4140
Department                  4140
Salary                      4140
dtype: int64

In [22]:
list(grp.groups.keys())

['IT',
 'RandD',
 'accounting',
 'hr',
 'management',
 'marketing',
 'product_mng',
 'sales',
 'support',
 'technical']

In [23]:
grp_sales[['Average_Monthly_Hours']].mean()

Average_Monthly_Hours    200.911353
dtype: float64

In [24]:
grp1 = df.groupby(['Department', 'Salary '])

In [25]:
grp1.get_group(('IT', 'low'))

,Employee_ID,Number_of_Projects,Average_Monthly_Hours,Time_Spent_in_Company,Work_Accident,Left,Promoted_in_Last_5_Years,Department,Salary
138,1849,4,249,5,0,1,0,IT,low
139,1852,5,257,5,0,1,0,IT,low
140,1863,6,245,4,0,1,0,IT,low
141,1864,2,155,3,0,1,0,IT,low
142,1865,6,256,4,0,1,0,IT,low
...,...,...,...,...,...,...,...,...,...
14807,86628,5,222,5,0,1,0,IT,low
14808,86641,6,263,4,0,1,0,IT,low
14809,14057,2,157,3,0,1,0,IT,low
14810,86651,7,307,4,0,1,0,IT,low
14815,86671,6,292,4,0,1,0,IT,low

In [26]:
# Pivot_Table 
#pivot_table = df.pivot_table(index='Department', columns='Salary ', values='Average_Monthly_Hours', aggfunc=np.mean)

df.pivot_table(index='Department', columns='Salary ', values='Average_Monthly_Hours', aggfunc=['min', 'max', 'count'])

             min             max             count
Salary      high low medium high  low medium  high   low medium
Department
IT           102  96     96  275  308    308    83   609    535
RandD        107  98     99  287  308    301    51   364    372
accounting    97  99    102  277  308    310    74   358    335
hr           133  98     98  289  310    310    45   335    359
management   106  97    102  286  307    304   225   180    225
marketing    113  98     96  286  310    300    80   402    376
product_mng  104  98    100  307  310    310    68   451    383
sales         96  96     97  306  307    310   269  2099   1772
support       99  96     97  286  310    310   141  1146    942
technical    103  97     97  284  310    310   201  1372   1147

In [27]:
df.pivot_table(index=['Department', 'Salary '], values=['Average_Monthly_Hours', 'Left'], aggfunc=['min', 'max', 'count'])

                                      min                        max       \
                    Average_Monthly_Hours Left Average_Monthly_Hours Left
Department  Salary
IT          high                      102    0                   275    1
            low                        96    0                   308    1
            medium                     96    0                   308    1
RandD       high                      107    0                   287    1
            low                        98    0                   308    1
            medium                     99    0                   301    1
accounting  high                       97    0                   277    1
            low                        99    0                   308    1
            medium                    102    0                   310    1
hr          high                      133    0                   289    1
            low                        98    0                   310    1
            medium                     98    0                   310    1
management  high                      106    0                   286    1
            low                        97    0                   307    1
            medium                    102    0                   304    1
marketing   high                      113    0                   286    1
            low                        98    0                   310    1
            medium                     96    0                   300    1
product_mng high                      104    0                   307    1
            low                        98    0                   310    1
            medium                    100    0                   310    1
sales       high                       96    0                   306    1
            low                        96    0                   307    1
            medium                     97    0                   310    1
support     high                       99    0                   286    1
            low                        96    0                   310    1
            medium                     97    0                   310    1
technical   high                      103    0                   284    1
            low                        97    0                   310    1
            medium                     97    0                   310    1

                                    count
                    Average_Monthly_Hours  Left
Department  Salary
IT          high                       83    83
            low                       609   609
            medium                    535   535
RandD       high                       51    51
            low                       364   364
            medium                    372   372
accounting  high                       74    74
            low                       358   358
            medium                    335   335
hr          high                       45    45
            low                       335   335
            medium                    359   359
management  high                      225   225
            low                       180   180
            medium                    225   225
marketing   high                       80    80
            low                       402   402
            medium                    376   376
product_mng high                       68    68
            low                       451   451
            medium                    383   383
sales       high                      269   269
            low                      2099  2099
            medium                   1772  1772
support     high                      141   141
            low                      1146  1146
            medium                    942   942
technical   high                      201   201
            low                      1372  1372
            medium                   1147  1147

In [29]:
df.pivot_table(index=['Department', 'Salary '], values=['Number_of_Projects'], aggfunc=['sum', 'min', 'max', 'count'])

                                   sum                min                max  \
                    Number_of_Projects Number_of_Projects Number_of_Projects
Department  Salary
IT          high                   321                  2                  6
            low                   2311                  2                  7
            medium                2051                  2                  7
RandD       high                   192                  2                  6
            low                   1385                  2                  7
            medium                1456                  2                  7
accounting  high                   289                  2                  6
            low                   1361                  2                  7
            medium                1284                  2                  7
hr          high                   175                  2                  6
            low                   1237                  2                  7
            medium                1289                  2                  7
management  high                   850                  2                  6
            low                    680                  2                  7
            medium                 902                  2                  7
marketing   high                   274                  2                  6
            low                   1508                  2                  7
            medium                1382                  2                  7
product_mng high                   252                  2                  6
            low                   1725                  2                  7
            medium                1457                  2                  7
sales       high                  1038                  2                  7
            low                   7888                  2                  7
            medium                6708                  2                  7
support     high                   535                  2                  6
            low                   4340                  2                  7
            medium                3604                  2                  7
technical   high                   734                  2                  6
            low                   5365                  2                  7
            medium                4449                  2                  7

                                 count
                    Number_of_Projects
Department  Salary
IT          high                    83
            low                    609
            medium                 535
RandD       high                    51
            low                    364
            medium                 372
accounting  high                    74
            low                    358
            medium                 335
hr          high                    45
            low                    335
            medium                 359
management  high                   225
            low                    180
            medium                 225
marketing   high                    80
            low                    402
            medium                 376
product_mng high                    68
            low                    451
            medium                 383
sales       high                   269
            low                   2099
            medium                1772
support     high                   141
            low                   1146
            medium                 942
technical   high                   201
            low                   1372
            medium                1147

In [30]:
df1 = pd.DataFrame({'a': [10, 20, 30, 40], 'b': [100, 200, 300, 400]})

df2 = pd.DataFrame({"a": [50, 60, 70, 80], "b": [500, 600, 700, 800]})

In [ ]:
#concat([df1,df2,....dfn], axis=0, ignore_index=True)  # axis=0 for row wise, axis=1 for column wise
pd.concat([df1, df2], axis=0,ignore_index=True)

    a    b
0  10  100
1  20  200
2  30  300
3  40  400
4  50  500
5  60  600
6  70  700
7  80  800

In [36]:
pd.concat([df1, df2], axis=1)

    a    b   a    b
0  10  100  50  500
1  20  200  60  600
2  30  300  70  700
3  40  400  80  800

In [37]:
df3 = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie'], 'age': [25, 30, 35]})
df4 = pd.DataFrame({'name': ['Alice', 'Bob', 'David'], 'city': ['New York', 'Los Angeles', 'Chicago']})

In [ ]:
#merge(df1,df2, on='column_name', how='inner')  # inner, outer, left, right

pd.merge(df3, df4, on='name',how='left')

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35          NaN

In [42]:
pd.merge(df3, df4, on='name',how='right')

    name   age         city
0  Alice  25.0     New York
1    Bob  30.0  Los Angeles
2  David   NaN      Chicago

In [45]:
df

,Employee_ID,Number_of_Projects,Average_Monthly_Hours,Time_Spent_in_Company,Work_Accident,Left,Promoted_in_Last_5_Years,Department,Salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low